export const TABLE_OF_CONTENTS = [
  { href: "#guide-overview-heading", label: "SVIP Gems Guide Overview" },
  { href: "#guide-hub-heading", label: "SVIP Gems Guide Pages" },
  { href: "#quick-info-heading", label: "Quick Info at a Glance" },
  { href: "#what-is-heading", label: "What Is SVIP Gems?" },
  { href: "#how-it-works-heading", label: "How SVIP Gems Works" },
  { href: "#download-install-heading", label: "Download & Install APK" },
  { href: "#registration-login-heading", label: "Registration & Login" },
  { href: "#deposit-withdraw-heading", label: "Deposit & Withdrawal" },
  { href: "#key-features-heading", label: "Key Features" },
  { href: "#popular-games-heading", label: "Popular Games" },
  { href: "#bonuses-heading", label: "Bonus System 2026" },
  { href: "#referral-heading", label: "Referral Program" },
  { href: "#screenshots-heading", label: "App Screenshots" },
  { href: "#why-choose-heading", label: "Why Choose SVIP Gems in Pakistan" },
  { href: "#real-or-fake-heading", label: "Real or Fake Review" },
  { href: "#reviews-heading", label: "User Reviews" },
  { href: "#safe-legal-heading", label: "Safety & Legal Status" },
  { href: "#pros-cons-heading", label: "Pros and Cons Summary" },
  { href: "#conclusion-heading", label: "Conclusion" },
  { href: "#faq-heading", label: "Frequently Asked Questions" },
] as const;
